using Microsoft.AspNetCore.Http;
using System.IO;
using System.Threading.Tasks;

namespace ExcelReadApi.Extensions
{
    public static class IformFileExtensions
    {
        public static async Task<string> GetTempFilePath(this IFormFile file)
        {
            var filePath = Path.GetTempFileName();

            using (var stream = File.Create(filePath))
            {
                // The formFile is the method parameter which type is IFormFile
                // Saves the files to the local file system using a file name generated by the app.
                await file.CopyToAsync(stream);
            }

            return filePath;
        }
    }
}
